MusikPortal/Models/AddSong.cs
using System.ComponentModel.DataAnnotations;

namespace MusikPortal.Models
{
    public class AddSong
    {
        [Required]
        [Display(Name = "enterName", ResourceType = typeof(Resources.Resource))]
        public string Name { get; set; }      
        public int StyleId  { get; set; }
        public int ArtistId { get; set; }
        [Required]
        [Display(Name = "Year", ResourceType = typeof(Resources.Resource))]
        public string Year { get; set; }
        [Required]
        [Display(Name = "Album", ResourceType = typeof(Resources.Resource))]
        public string Album{ get; set; }
        [Required]
        [Display(Name = "Text", ResourceType = typeof(Resources.Resource))]
        public string text { get; set; }      
        [Display(Name = "File", ResourceType = typeof(Resources.Resource))]
        public string? file { get; set; }
        public int? SongId { get; set; }
    }
}

MusikPortal/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using MusikPortal.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using MusicPortal.BLL.Interfaces;
using MusicPortal.BLL.DTO;
using MusicPortal.BLL.Services;
using MusicPortal.Filters;
using Microsoft.AspNetCore.SignalR;
using MusicPortal;

namespace MusikPortal.Controllers
{
    [Culture]
    public class SongController : Controller
    {
        IWebHostEnvironment _appEnvironment;
        IHubContext<NotificationHub> hubContext { get; }
        private readonly ISongService songService;
        private readonly IArtistService artistService;
        private readonly IStyleService styleService;
        public SongController(ISongService s, IArtistService a, IStyleService st,
            IWebHostEnvironment appEnvironment, IHubContext<NotificationHub> hub)
        {
            songService = s;
            artistService = a;
            styleService = st;
            _appEnvironment = appEnvironment;
            hubContext = hub;
        }
        private async Task SendMessage(string message)
        {
            // Вызов метода displayMessage на всех клиентах, пуш уведомления при изменениях в БД
            await hubContext.Clients.All.SendAsync("displayMessage", message);
        }
        public async Task<IActionResult> Create()
        {
            HttpContext.Session.SetString("path", Request.Path);
            await putStylesArtists();
            return View("AddSong");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( AddSong song, IFormFile uploadedFile)
        {
            HttpContext.Session.SetString("path", Request.Path);
            if (uploadedFile == null)
                ModelState.AddModelError("", "put the file");
            DateTime today = DateTime.Today;
            int currentYear = today.Year;
            try
            {
                if (Convert.ToInt32(song.Year) < 0 || Convert.ToInt32(song.Year) > currentYear)
                    ModelState.AddModelError("", "uncorrectly year");
            }
            catch { ModelState.AddModelError("", "uncorrectly year"); }
            if (uploadedFile != null)
            {
                string str= uploadedFile.FileName.Replace(" ", "_");
                string str1 = str.Replace("-", "_");
                // Путь к папке Files
                string path = "/MusicFiles/" + str1; // имя файла

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream); // копируем файл в поток
                }
                SongDTO s = new();
                StyleDTO sStyle = await styleService.GetStyle(song.StyleId);
                ArtistDTO aArtist = await artistService.GetArtist(song.ArtistId);
                s.Name = song.Name;
                s.style =sStyle.Name;
                s.styleId = sStyle.Id;
                s.artist = aArtist.Name;
                s.artistId = aArtist.Id;
                s.Year = song.Year;
                s.text = song.text;
                s.Album=song.Album; 
                s.file = path;
                if (ModelState.IsValid)
                {
                    try
                    {
                        await songService.AddSong(s);
                        await SendMessage("AdSong" + s.Name);
                        await songService.AddSongToArtist(song.ArtistId, s);
                     
                        return RedirectToAction("Index", "Home");
                    }
                    catch
                    {
                        await putStylesArtists();
                        return View("AddSong", song);
                    }
                }
                else
                {
                    await putStylesArtists();
                    return View("AddSong", song);
                }
            }
            await putStylesArtists();
            return View("AddSong", song);
        }
        public async Task putStylesArtists()
        {           
            IEnumerable<StyleDTO> s = await styleService.GetAllStyles();
            IEnumerable<ArtistDTO> a = await artistService.GetAllArtists();
            ViewData["StyleId"] = new SelectList(s, "Id", "Name");
            ViewData["ArtistId"] = new SelectList(a, "Id", "Name");
        }
       
    }
}

MusikPortal/Views/Song/AddSong.cshtml
@{
    Layout = "_Login";
}
@model MusikPortal.Models.AddSong

<h3 class=" b1 b3 center c20 pr">@Resources.Resource.AddSong</h3>
<div class="center">
        <div class="card c77">
            <form asp-action="Create" asp-controller="Song" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
                <label>@Resources.Resource.Listofartists</label>
            <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
            <span asp-validation-for="ArtistId" class="text-danger"></span>
        </div>
                <div class="form-group">
                <span>@Resources.Resource.Songname </span><br />
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                <label>@Resources.Resource.Listofstyles</label>
                    <select asp-for="StyleId" class="form-control" asp-items="ViewBag.StyleId"></select>
                    <span asp-validation-for="StyleId" class="text-danger"></span>
                </div>
                <div class="form-group">
                <span>@Resources.Resource.Year</span><br />
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
        <div class="form-group">
                <span>@Resources.Resource.Album</span><br />
            <input asp-for="Album" class="form-control" />
            <span asp-validation-for="Album" class="text-danger"></span>
        </div>
                <div class="form-group">
                <span>@Resources.Resource.Text</span><br />
                    <textarea asp-for="text" class="c17"></textarea><br />
                    <span asp-validation-for="text" class="text-danger"></span>
                </div>               
                <input type="file" name="uploadedFile" accept=".mp4, .mp3" />
                <div class="form-group">
                    <br />
                <input type="submit" value="@Resources.Resource.AddSong" class="btn btn-primary c2" />
                </div>
            </form>
        </div>
        </div>